name: DevSkim

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch
  schedule:
    - cron: '30 0 * * 0'  # Weekly on Sunday at 00:30 UTC

permissions:
  contents: read

jobs:
  devskim:
    uses: drasi-project/.github/.github/workflows/devskim.yaml@main
